export const ICON_SIZES = {
  inline: 16,
  button: 18,
  default: 20,
  navigation: 24,
  feature: 28,
  hero: 32,
  emptyState: 40,
} as const;

export const UI_ICONS = {
  add: 'solar:add-circle-linear',
  back: 'solar:alt-arrow-left-linear',
  close: 'solar:close-circle-linear',
  collapse: 'solar:alt-arrow-up-linear',
  expand: 'solar:alt-arrow-down-linear',
  forward: 'solar:alt-arrow-right-linear',
  info: 'solar:info-circle-linear',
  hide: 'solar:eye-closed-linear',
  logout: 'solar:logout-2-linear',
  more: 'solar:menu-dots-bold',
  search: 'solar:magnifier-linear',
  show: 'solar:eye-linear',
  success: 'solar:check-circle-bold',
  upload: 'solar:cloud-upload-bold-duotone',
  warning: 'solar:danger-triangle-bold',
} as const;

export const ACTION_ICONS = {
  accounts: 'solar:wallet-money-bold-duotone',
  bankAccount: 'solar:buildings-2-bold-duotone',
  beneficiaries: 'solar:user-id-bold-duotone',
  copy: 'solar:copy-linear',
  cryptoWallet: 'solar:wallet-2-bold-duotone',
  customers: 'solar:users-group-rounded-bold-duotone',
  edit: 'solar:pen-bold',
  exchange: 'solar:refresh-square-bold-duotone',
  fundsIn: 'solar:download-minimalistic-bold-duotone',
  fundsOut: 'solar:upload-minimalistic-bold-duotone',
  fundingChannel: 'solar:card-transfer-bold-duotone',
  history: 'solar:history-bold-duotone',
  home: 'solar:home-2-bold-duotone',
  internalTransfer: 'solar:transfer-horizontal-bold-duotone',
  notifications: 'solar:bell-bing-bold-duotone',
  onboarding: 'solar:user-plus-bold-duotone',
  otc: 'solar:hand-money-bold-duotone',
  refresh: 'solar:refresh-linear',
  settings: 'solar:settings-bold-duotone',
} as const;

const LEGACY_UI_ICON_ALIASES: Record<string, string> = {
  'eva:arrow-back-fill': UI_ICONS.back,
  'eva:arrow-forward-fill': UI_ICONS.forward,
  'eva:arrow-ios-back-fill': UI_ICONS.back,
  'eva:arrow-ios-downward-fill': UI_ICONS.expand,
  'eva:arrow-ios-forward-fill': UI_ICONS.forward,
  'eva:arrow-ios-upward-fill': UI_ICONS.collapse,
  'eva:alert-triangle-fill': UI_ICONS.warning,
  'eva:checkmark-circle-2-fill': UI_ICONS.success,
  'eva:cloud-upload-fill': UI_ICONS.upload,
  'eva:close-fill': UI_ICONS.close,
  'eva:info-fill': UI_ICONS.info,
  'eva:info-outline': UI_ICONS.info,
  'eva:more-horizontal-fill': UI_ICONS.more,
  'eva:search-fill': UI_ICONS.search,
  'mingcute:add-line': UI_ICONS.add,
  'mingcute:close-line': UI_ICONS.close,
  'solar:add-circle-bold': UI_ICONS.add,
  'solar:bank-bold-duotone': ACTION_ICONS.bankAccount,
  'solar:copy-bold': ACTION_ICONS.copy,
  'solar:copy-bold-duotone': ACTION_ICONS.copy,
  'solar:copy-outline': ACTION_ICONS.copy,
  'solar:download-minimalistic-bold': ACTION_ICONS.fundsIn,
  'solar:download-square-bold-duotone': ACTION_ICONS.fundsIn,
  'solar:eye-bold': UI_ICONS.show,
  'solar:eye-closed-bold': UI_ICONS.hide,
  'solar:history-bold': ACTION_ICONS.history,
  'solar:home-2-bold': ACTION_ICONS.home,
  'solar:inbox-in-bold-duotone': ACTION_ICONS.fundsIn,
  'solar:logout-2-bold-duotone': UI_ICONS.logout,
  'solar:magnifer-linear': UI_ICONS.search,
  'solar:outbox-bold-duotone': ACTION_ICONS.fundsOut,
  'solar:pen-new-square-bold-duotone': ACTION_ICONS.edit,
  'solar:refresh-bold': ACTION_ICONS.refresh,
  'solar:settings-linear': ACTION_ICONS.settings,
  'solar:transfer-horizontal-bold': ACTION_ICONS.internalTransfer,
  'solar:upload-minimalistic-bold': ACTION_ICONS.fundsOut,
  'solar:upload-square-bold-duotone': ACTION_ICONS.fundsOut,
  'solar:user-id-bold': ACTION_ICONS.beneficiaries,
  'solar:user-plus-bold': ACTION_ICONS.onboarding,
  'solar:user-plus-rounded-bold-duotone': ACTION_ICONS.onboarding,
};

export function normalizeUiIcon(icon: string) {
  return LEGACY_UI_ICON_ALIASES[icon] || icon;
}
