export const NEOBANK_DEPLOYMENT_MODE =
  process.env.REACT_APP_NEOBANK_DEPLOYMENT_MODE || 'full-admin-wallet';

export const IS_ISOLATED_WALLET_DEPLOYMENT = NEOBANK_DEPLOYMENT_MODE === 'isolated-wallet';

export const IS_FULL_ADMIN_WALLET_DEPLOYMENT = NEOBANK_DEPLOYMENT_MODE === 'full-admin-wallet';

export const IS_NEOBANK_DEPLOYMENT =
  IS_ISOLATED_WALLET_DEPLOYMENT || IS_FULL_ADMIN_WALLET_DEPLOYMENT;
